# golangci-lint configuration
# Reference: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    # removed gosimple because it is deprecated => in v2 it was merged into staticcheck
    - gocyclo
    - misspell
    - gocritic
  settings:
    errcheck:
      check-type-assertions: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
