sonar.projectKey=benjamingolic_cd-mcm-exercise-Golic
sonar.organization=benjamingolic
sonar.projectName=cd-mcm-exercise-Golic # from sonarqube-scan instructions
sonar.projectVersion=1.0 # from sonarqube-scan instructions

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8